# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V74RdDELtxjgFBhTU4s2d83HIOCNfD5T
"""

class SimpleReflexAgent:

    def __init__(self):
        self.position = "A"

    def act(self, environment):
        current_status = environment[self.position]

        if current_status == "Dirty":
            action = "Suck"
            environment[self.position] = "Clean"

        elif self.position == "A":
            action = "Move Right"
            self.position = "B"

        else:
            action = "Move Left"
            self.position = "A"

        return action


class GoalBasedAgent:

    def __init__(self):
        self.position = "A"
        self.goal = {
            "A": "Clean",
            "B": "Clean"
        }

    def goal_reached(self, environment):
        return (
            environment["A"] == "Clean"
            and environment["B"] == "Clean"
        )

    def act(self, environment):

        if self.goal_reached(environment):
            return "Goal Reached"

        current_status = environment[self.position]

        if current_status == "Dirty":
            action = "Suck"
            environment[self.position] = "Clean"

        elif self.position == "A":
            action = "Move Right"
            self.position = "B"

        else:
            action = "Move Left"
            self.position = "A"

        return action


def display_environment(environment, position):
    print("\nEnvironment:")

    for room in ["A", "B"]:
        print(
            "Room", room, "=", environment[room],
            "<-- Agent" if room == position else ""
        )


print("==========================================")
print("       VACUUM CLEANER AI AGENT")
print("==========================================")

print("\n1. SIMPLE REFLEX AGENT")
print("2. GOAL-BASED AGENT")

choice = int(input("\nEnter your choice: "))

environment = {
    "A": "Dirty",
    "B": "Dirty"
}

if choice == 1:

    agent = SimpleReflexAgent()

    print("\n--- SIMPLE REFLEX AGENT ---")

    display_environment(environment, agent.position)

    for step in range(10):

        action = agent.act(environment)

        print("\nStep", step + 1)
        print("Action:", action)

        display_environment(environment, agent.position)

        if environment["A"] == "Clean" and environment["B"] == "Clean":
            print("\nBoth rooms are CLEAN.")
            break

elif choice == 2:

    agent = GoalBasedAgent()

    print("\n--- GOAL-BASED AGENT ---")
    print("Goal: Make both rooms CLEAN.")

    display_environment(environment, agent.position)

    for step in range(10):

        action = agent.act(environment)

        print("\nStep", step + 1)
        print("Action:", action)

        display_environment(environment, agent.position)

        if agent.goal_reached(environment):
            print("\nGOAL ACHIEVED!")
            print("Both rooms are CLEAN.")
            break

else:
    print("Invalid choice!")